
elasticsearch:
  elastic-endpoint: 172.16.14.182:9300

# Minio的配置，这是一个用于开发测试的 minio 地址.
minio:
  endpoint: http://127.0.0.1:9000
  access-key: minio
  secret-key: 12345678
  bucket: image-host
spring:
  profiles:
    active: local
